#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[java]

  - name: centos-6.5
    run_list:
      - recipe[yum]
      - recipe[java]

suites:
  - name: basic_lwrp
    run_list:
      - recipe[tomcat_test_basic_lwrp]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
